### ISSUE TITLE
Recreate Symlinks

### ISSUE THREAD

**Issue by tooliload** [OpenMediaVault-Plugin-Developers/openmediavault-symlinks#2]
Hi, is there a way to re-create all symlinks there stored in confix.xml? I have change my hdd in omv, but re-use the same uuid of hdd. All created symlinks not there on new hdd. Is there a way to re-create it by plugin? (i found out, if i deactivate and active the entry, that symlinks will create, but i have many symlinks on system). 

Thanks for help

**Comment by ryecoaaron** [comment]
Not really.  The symlinks are created at creation time but there is no script that could be run that would loop through the list.  I guess I could see what it would take to script it.

**Comment by ryecoaaron** [comment]
`
#!/bin/bash

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

XPATH="/config/services/symlinks/symlinks/symlink"

count=$(omv_config_get_count "${XPATH}")
index=0
while [ ${index} -le ${count} ]; do
    enable=$(omv_config_get "${XPATH}[position()=${index}]/enable")
    src=$(omv_config_get "${XPATH}[position()=${index}]/source")
    dest=$(omv_config_get "${XPATH}[position()=${index}]/destination")
    index=$(( ${index} + 1 ))
    if [ -z "${src}" ]; then
        continue
    fi
    if [ "${enable}" != "0" ]; then
        ln -s "${src}" "${dest}"
    fi
done
`

**Comment by tooliload** [comment]
Thanks a lot. Work great.
