### ISSUE TITLE
Move to Storage menu section

### ISSUE THREAD

**Issue by silopolis** [OpenMediaVault-Plugin-Developers/openmediavault-symlinks#3]
re,

As this is really related to storage management, this would better be filled under the ad-hoc section... At least I always have to think twice before going to it

TY

**Comment by ryecoaaron** [comment]
It is not creating any storage.  It is really path management which I consider a service.

**Comment by silopolis** [comment]
Le ven. 10 juin 2022 à 15:38, Aaron Murray ***@***.***> a
écrit :

> It is not creating any storage. It is really path management which I
> consider a service
>

Isn't path management really just a part of storage management?!

**Comment by ryecoaaron** [comment]
Half the plugins could probably be part of storage management in some way.  I've had this discussion with Volker a few times and he envisioned that most plugins would be in the Services section.
